apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 2
  selector:
    matchLabels:
      name: was
  template:
    metadata:
      labels:
        name: was
    spec:
      containers:
        - image: gangseodelpiero/pet-was
          name: was
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: was-svc
spec:
  type: ClusterIP
  clusterIP: 10.100.10.10
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: was
